name: thumblr
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      macos:
        default_package: thumblr_macos

dependencies:
  flutter:
    sdk: flutter
  thumblr_platform_interface:
    path: ../thumblr_platform_interface
  thumblr_macos:
    path: ../thumblr_macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  plugin_platform_interface: ^2.0.0

