name: thumblr
description: A federated Flutter plugin for generating video thumbnails on desktop platforms
version: 0.0.2
homepage: https://github.com/GroovinChip/thumblr/tree/main/thumblr

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      macos:
        default_package: thumblr_macos
      windows:
        default_package: thumblr_windows

dependencies:
  flutter:
    sdk: flutter
  thumblr_platform_interface: ^0.2.0
  thumblr_macos: ^0.2.0
  thumblr_windows: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  plugin_platform_interface: ^2.0.0

