name: thumblr_macos
description: The macOS implementation of the thumblr plugin.
version: 0.1.1
homepage: https://github.com/GroovinChip/thumblr/tree/main/thumblr_macos

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  thumblr_platform_interface: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: thumblr
    platforms:
      macos:
        dartPluginClass: ThumblrMacOS
        pluginClass: ThumblrMacosPlugin
