name: thumblr_web
description: The web implementation of the thumblr plugin.
version: 0.0.1
homepage: https://github.com/GroovinChip/thumblr/tree/main/thumblr_web

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  thumblr_platform_interface: ^0.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ThumblrWeb
        fileName: thumblr_web.dart
